perma: pretty
theme: jekyll_patternbot

patternbot:
  title: "Best Foot Forward"
  description: |
    Best Foot Forward is a large sock corporation that specializes in releasing people's creativity and wellness from within. There are many homeless Canadians and most of them have inadequate clothing. Together, we can help reduce this problem.
  font_url: "https://fonts.googleapis.com/css?family=Bebas+Neue|Overpass:400,700,900&display=swap"
  colors:
    background: "#fff"
    accent: "--color-secondary"
  rationales:
    typefaces.primary: |
      Overpass was selected because it is a modern font and easy to read. Overpass is to be used for all body copy.
    typefaces.secondary: |
      Bebas Neue is only to be used for highlighting text: headings, buttons, banners, etc.
    colors.primary: |
      The primary color is to represent the warmness we are trying to bring to people.
    colors.secondary: |
      The secondary color is a blue to represent the coldness we are trying to prevent.
