permalink: pretty
theme: jekyll_patternbot

patternbot:
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header & footer.
  title: "Best Foot Forward"
  description: |
    Best Foot Forward is a large sock corporation that specializes in releasing people's creativity and wellness from within. There are many homeless Canadians and most of them have inadequate clothing. Together, we can help reduce this problem.
  font_url: "https://fonts.googleapis.com/css?family=Bebas+Neue|Overpass:400,700,900&display=swap"
  colors:
    background: "#fff"
    accent: "--color-primary"
  rationales:
    typefaces.primary: |
      Overpass was selected because it is a modern font and easy to read. Overpass is to be used for all body copy.
    typefaces.secondary: |
      Bebas Neue is only to be used for highlighting text: headings, buttons, banners, etc.
    colors.primary: |
        The primary color is a blue to represent the coldness we are trying to prevent.
    colors.secondary: |
      The secondary color is a pink to represent the warmness we are trying to bring to people.
