title: "Cards"
description: |
  The card provides information and clicking on it user can get even more information.

patterns:
  product-card:
    width: 400
    description: |
      The product card is used on the product listing pages to display each available product.
    fields:
    - name: data
      type: object
      data:
        source: "site.products[0]"
        type: Product

  collections-card:
    width: 400
    description: |
      The collections card is displayed on most pages to show the current collections available.
    fields:
    - name: data
      type: object
      example: "/images/summer.jpg"

  category-card:
    width: 400
    description: |
      The category card is used on the homepage to display how the socks are categorized.
