title: "Cards"
description: |
  The card provides information and clicking on it user can get even more information.

patterns:
  product-card:
    width: 400
    description: |
      The product card is used on the product listing pages to display each available product.
  collections-card:
    width: 400
    description: |
      The collections card is displayed on most pages to show the current collections available.
  category-card:
    width: 400
    description: |
      The category card is used on the homepage to display how the socks are categorized.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
      - name: category
        type: string
        example: "Men's"
        required: false
      - name: desc
        type: string
        example: "Placeholder text"
        required: false
      - name: button-1
        type: string
        example: "/products/"
      - name: collection
        type: string
        example: "Summer"
        required: false
