title: "Banners"
description: |
  Banners are to be placed at the top of every page to let users know their location.

patterns:
  banner:
    description: |
      The main banner is displayed only on the homepage to update users on what's going on.
    fields:
    - name: 'heading'
      type: 'string'
      example: "New Arrivals"
    - name: 'text'
      type: 'string'
      example: "This is some placeholder text!"

  secondary-banner:
    description: |
      The secondary banner is used at the top of all other pages to let users know their location.
    fields:
      - name: heading-2
        type: string
        example: "Shop"
